
name: Build and Push Docker Image

on:
  push:
    paths:
      - main_python/** # Change this to custom trigger when you want this to run.

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERPW }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t cell_counter_image .

    - name: Tag Docker image
      run: docker tag cell_counter_image engpol/cell_counter_image:latest

    - name: Push Docker image to Docker Hub
      run: docker push engpol/cell_counter_image:latest

