name: Build and Push Docker Image to GitHub Packages
## This is for pushing the cell counter docker image to the packages of my repo. Does not build the image from scratch, use other workflow to update the image if need be. 
on: 
  push: 
    paths: 
      - main_python/** 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/cell_counter_image:latest .

    - name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/${{ github.repository }}/cell_counter_image:latest
