name: Image Processing Workflow

on:
  push:
    paths:
      - cell_images/**  # Monitor changes in the 'input' folder for uploaded images

jobs:
  process_image:
    runs-on: ubuntu-24.04


    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        docker build -t cell_counter_image .
        echo "${{ secrets.DOCKERPW }}" | docker login -u "engpol" --password-stdin
        docker tag cell_counter_image engpol/cell_counter_image:latest
        docker push engpol/cell_counter_image:latest
