name: Process Images with Docker

on:
  push:
    branches:
      - main
#on:
 # push:
  #  paths:
   #   - cell_images/**  # Trigger on changes to the input folder

jobs:
  process_image:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner to orchestrate the container
    container:
      image: ghcr.io/engpol/cell_counter_pub/cell_counter_image:latest  # Use your GitHub Package image

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run image processing script
      env:
        GITHUB_TOKEN: ${{ secrets.PATOKEN }}
      run: python main_python/cell_count.py
